"""add job dependencies and ai_summary cache

Revision ID: 7bd6afb1d2a3
Revises: 6ebf7d144501
Create Date: 2026-07-02 15:56:50.772517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bd6afb1d2a3'
down_revision: Union[str, None] = '6ebf7d144501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_dependencies',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_job_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('job_id != depends_on_job_id', name='ck_job_dependency_not_self'),
    sa.ForeignKeyConstraint(['depends_on_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'depends_on_job_id', name='uq_job_dependency')
    )
    op.create_index(op.f('ix_job_dependencies_depends_on_job_id'), 'job_dependencies', ['depends_on_job_id'], unique=False)
    op.create_index(op.f('ix_job_dependencies_job_id'), 'job_dependencies', ['job_id'], unique=False)
    op.add_column('job_executions', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_executions', 'ai_summary')
    op.drop_index(op.f('ix_job_dependencies_job_id'), table_name='job_dependencies')
    op.drop_index(op.f('ix_job_dependencies_depends_on_job_id'), table_name='job_dependencies')
    op.drop_table('job_dependencies')
    # ### end Alembic commands ###
